In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10) #平均が0分散が1（正規分布）

In [7]:
A

array([ 0.03328118,  0.76559671,  0.19253755, -0.19177384, -0.52131763,
        2.09766337, -1.35355758,  0.58571753,  0.05074567,  0.86991662])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 0.00284617,  1.46485567,  0.56100228,  1.09540545,  0.19877316,
       -0.89801031, -0.4953607 , -1.74897258, -0.62411031, -2.04239348])

In [10]:
np.add(A,B)

array([ 0.03612735,  2.23045239,  0.75353983,  0.90363161, -0.32254447,
        1.19965306, -1.84891828, -1.16325505, -0.57336465, -1.17247686])

In [ ]:
np