In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [16]:
pd.concat([ser1,ser2,ser1],axis=1,sort=False)

0    1    2
T  0.0  NaN  0.0
U  1.0  NaN  1.0
V  2.0  NaN  2.0
X  NaN  3.0  NaN
Y  NaN  4.0  NaN

In [17]:
pd.concat([ser1,ser2,ser1],axis=1,sort=True)

0    1    2
T  0.0  NaN  0.0
U  1.0  NaN  1.0
V  2.0  NaN  2.0
X  NaN  3.0  NaN
Y  NaN  4.0  NaN

In [18]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [20]:
pd.concat([ser1,ser2],keys=['cat1','cat2'],axis=1,sort=False)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [2]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe1

X         Y         Z
0  0.247537  0.709858  0.079058
1 -0.475126  1.304212 -0.839214
2 -0.861471 -0.149401 -1.006320
3  2.435925 -0.253115 -0.795290

In [3]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])
dframe2

Y         Q         X
0 -0.231947 -1.301540 -0.912535
1  0.690480 -1.575035  1.389012
2  0.711764  0.234336  0.722440

In [24]:
pd.concat([dframe1,dframe2],sort=False)

X         Y         Z         Q
0  0.511201 -1.185209  0.886253       NaN
1 -1.407944 -0.264479 -0.017208       NaN
2  1.772365  1.559004  1.627082       NaN
3  0.479851  1.752218  0.216611       NaN
0 -1.951474 -0.765913       NaN -0.574780
1 -0.573189  1.754369       NaN -0.097807
2  1.127819  0.198270       NaN -0.332716

In [4]:
pd.concat([dframe1,dframe2],sort=False,axis=1)

X         Y         Z         Y         Q         X
0  0.247537  0.709858  0.079058 -0.231947 -1.301540 -0.912535
1 -0.475126  1.304212 -0.839214  0.690480 -1.575035  1.389012
2 -0.861471 -0.149401 -1.006320  0.711764  0.234336  0.722440
3  2.435925 -0.253115 -0.795290       NaN       NaN       NaN

In [5]:
pd.concat([dframe1,dframe2],sort=False,ignore_index=True)

X         Y         Z         Q
0  0.247537  0.709858  0.079058       NaN
1 -0.475126  1.304212 -0.839214       NaN
2 -0.861471 -0.149401 -1.006320       NaN
3  2.435925 -0.253115 -0.795290       NaN
4 -0.912535 -0.231947       NaN -1.301540
5  1.389012  0.690480       NaN -1.575035
6  0.722440  0.711764       NaN  0.234336

In [6]:
pd.concat([dframe2,dframe1],sort=False,ignore_index=True)

Y         Q         X         Z
0 -0.231947 -1.301540 -0.912535       NaN
1  0.690480 -1.575035  1.389012       NaN
2  0.711764  0.234336  0.722440       NaN
3  0.709858       NaN  0.247537  0.079058
4  1.304212       NaN -0.475126 -0.839214
5 -0.149401       NaN -0.861471 -1.006320
6 -0.253115       NaN  2.435925 -0.795290